### ISSUE TITLE
Electrical panel duplicated

### ISSUE THREAD

**Issue by PanmanS** [PeasantFoundry/Mechtrauma#15]
there are currently 2 electrical panels that serve exactly same purpose (and no, it is not fuse panel)
![image](https://user-images.githubusercontent.com/42521948/210298773-ae96696e-23fb-4bf7-bf20-bea8fa9da020.png)

**Comment by PeasantFoundry** [comment]
I will update the legacy panel to be not viewable in the editor. The electrical panels in the ALPHA mod have two power pins; however, Torca identified a problem with this deployment that wasn't identified in my testing. The reason I'm forking the panels is that if I just update the panels and push the update it will break existing subs that are using both power pins. For compatibility sake I'll keep the old panels (since they work for the most part) and have version 2 be the only panel going forward.

**Comment by PeasantFoundry** [comment]
identifier="electrical_panel" now has hideinmenus="true"

**Comment by PanmanS** [comment]
Aight, this sounds cool
