### ISSUE TITLE
Generators still work in editor (nvm, S3000D does it too, even after update)

### ISSUE THREAD

**Issue by PanmanS** [PeasantFoundry/Mechtrauma#25]
Still the same issue as before: they work while being in editor!

**Comment by PeasantFoundry** [comment]
Found another issue with the GameIsRunning function. Apparently, Game.Paused is only for single player. I've updated the function to have separate logic for single player vs multiplayer (client/sever). that *should* do the trick. Also, you may want to type "fixitems" into the console and save your sub so that you don't have to repair the oil/filters/etc that were being burned previously and saved in a used state.
